# You are building the track lifecycle manager for a retail store CCTV analytics pipeline.

# FILE: pipeline/tracker.py
# PURPOSE: Maintain the state of all active person tracks across frames. Handles visitor_id
# assignment, zone transition logic, and dwell timer management. Coordinates between the
# YOLO ByteTrack output and the event emitter.

# TECH: Python 3.11, numpy==1.26.4, dataclasses, datetime, typing

# CONTEXT:
# - YOLOv8's `model.track()` with `tracker="bytetrack.yaml"` returns Results objects.
#   Each detection has: xyxy (bbox), track_id (int), conf (float).
# - A "track" is a single person tracked across frames by ByteTrack. track_id is stable
#   within a clip but resets between clips.
# - A "visitor" maps to a visitor_id (generated by ReIDEngine) that can span multiple clips.
# - Zone transitions: ZONE_ENTER when person moves into a new zone, ZONE_EXIT when they leave.
# - ZONE_DWELL: emit every 30 seconds of continuous zone presence (configurable).
# - Tracks not seen for more than 90 frames (6 seconds at 15fps with frame_skip=3)
#   are considered "lost" and trigger EXIT events.

# IMPLEMENT THE FOLLOWING:

# 1. `@dataclass class TrackState:`
#    - track_id: int
#    - visitor_id: str
#    - camera_id: str
#    - store_id: str
#    - current_zone: Optional[str] = None
#    - zone_entry_frame: Optional[int] = None
#    - last_dwell_emit_frame: Optional[int] = None
#    - entry_frame: int = 0
#    - is_staff: bool = False
#    - embedding: Optional[np.ndarray] = None  # field(default=None, repr=False)
#    - session_seq: int = 0
#    - last_seen_frame: int = 0
#    - has_entered: bool = False  # True after ENTRY event emitted
#    - zones_visited: list = field(default_factory=list)  # for zone ubiquity check

# 2. `class TrackManager:`

#    `__init__(self, camera_id: str, store_id: str, fps: float,
#              dwell_threshold_seconds: int = 30, lost_track_frames: int = 90):`
#    - `self.camera_id = camera_id`
#    - `self.store_id = store_id`
#    - `self.fps = fps`
#    - `self.dwell_threshold_frames = int(dwell_threshold_seconds * fps)`
#    - `self.lost_track_frames = lost_track_frames`
#    - `self.active_tracks: dict[int, TrackState]` — keyed by track_id
#    - `self.frame_counter: int = 0`

#    `update(self, detections: list[dict]) -> dict:`
#    - detections: list of {"track_id": int, "bbox_xyxy": list[float],
#                            "confidence": float, "zone_id": str|None,
#                            "is_staff": bool, "visitor_id": str}
#    - For each detection:
#      - If track_id not in active_tracks: create new TrackState.
#      - Update last_seen_frame, current_zone, embedding (if provided).
#    - Detect lost tracks: any active track not in current detection set for > lost_track_frames.
#    - Returns:
#      {
#        "new_tracks": list[TrackState],       # first frame seen
#        "updated_tracks": list[TrackState],   # ongoing
#        "lost_tracks": list[TrackState],      # must emit EXIT
#        "zone_entries": list[tuple[TrackState, str]],  # (track, new_zone_id)
#        "zone_exits": list[tuple[TrackState, str]],    # (track, old_zone_id)
#        "dwell_events": list[tuple[TrackState, str, int]]  # (track, zone_id, dwell_ms)
#      }
#    - For zone_entries/exits: compare current_zone vs previous zone in track state.
#    - For dwell_events: check if (frame_counter - zone_entry_frame) >= dwell_threshold_frames
#      AND (frame_counter - last_dwell_emit_frame) >= dwell_threshold_frames.
#    - Increment frame_counter.

#    `get_active_billing_track_ids(self, billing_zone_ids: list[str]) -> set[int]:`
#    - Returns set of track_ids whose current_zone is in billing_zone_ids.

#    `get_all_active(self) -> dict[int, TrackState]:`
#    - Returns copy of self.active_tracks.

#    `remove_track(self, track_id: int) -> Optional[TrackState]:`
#    - Pop and return the TrackState. Returns None if not found.

#    `clear_all(self) -> list[TrackState]:`
#    - Close all active tracks, return them as a list (for final EXIT events at clip end).
#    - Clear self.active_tracks.

# IMPORTS NEEDED: dataclasses (dataclass, field), numpy as np, datetime, typing (Optional), copy
